# Generated by Django 5.2.17 on 2026-08-14 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enhancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wiki_title', models.CharField(max_length=255, unique=True)),
                ('wiki_page_id', models.PositiveIntegerField(unique=True)),
                ('item_type', models.CharField(blank=True, max_length=255)),
                ('minimum_level', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemEnhancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('raw_template', models.CharField(blank=True, max_length=500)),
                ('enhancement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.enhancement')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhancements', to='catalog.item')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'enhancement', 'value'), name='unique_item_enhancement')],
            },
        ),
    ]
