# Generated by Django 5.2.17 on 2026-08-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wiki_revision_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
