# Generated by Django 5.2.17 on 2026-08-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_wiki_revision_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='wiki_revision_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
