# Generated by Django 5.2.17 on 2026-08-15 00:05

from django.db import migrations, models


def backfill_item_kind(apps, schema_editor):
    Item = apps.get_model("catalog", "Item")
    Item.objects.filter(item_kind="").update(item_kind="Named item")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_item_wiki_revision_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_kind',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(
            backfill_item_kind,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_kind',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
