# Generated by Django 5.2.17 on 2026-08-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_item_item_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255, unique=True)),
                ('scope', models.CharField(choices=[('list', 'Enhancement list'), ('item', 'Item-wide')], default='list', max_length=10)),
                ('handler', models.CharField(max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'template_name'],
            },
        ),
    ]
