# Generated by Django 5.2.17 on 2026-08-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_seed_enhancement_rules'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemenhancement',
            name='unique_item_enhancement',
        ),
        migrations.AddField(
            model_name='itemenhancement',
            name='detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='itemenhancement',
            constraint=models.UniqueConstraint(fields=('item', 'enhancement', 'value', 'detail'), name='unique_item_enhancement'),
        ),
    ]
