# Generated by Django 5.2.17 on 2026-08-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_itemenhancement_unique_item_enhancement_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemenhancement',
            name='unique_item_enhancement',
        ),
        migrations.AddField(
            model_name='itemenhancement',
            name='tier',
            field=models.PositiveIntegerField(blank=True, help_text='Upgrade tier number when this enhancement only exists after an item upgrade; blank for base.', null=True),
        ),
        migrations.AddConstraint(
            model_name='itemenhancement',
            constraint=models.UniqueConstraint(fields=('item', 'enhancement', 'value', 'detail', 'tier'), name='unique_item_enhancement'),
        ),
    ]
