# Generated by Django 5.2.17 on 2026-08-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_itemenhancement_unique_item_enhancement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancementRender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_call', models.CharField(help_text='Exact template call, e.g. {{Absorption|Fire|26}}.', max_length=500, unique=True)),
                ('canonical_name', models.CharField(help_text='Enhancement name the wiki links to, e.g. Energy Absorption.', max_length=255)),
                ('display_text', models.CharField(help_text='Exact text the wiki renders for this template call, e.g. Fire Absorption +26%.', max_length=500)),
                ('rendered_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='itemenhancement',
            name='unique_item_enhancement',
        ),
        migrations.AddField(
            model_name='itemenhancement',
            name='display_text',
            field=models.CharField(blank=True, help_text='Verbatim display text from the wiki render cache; overrides display_name composition.', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='itemenhancement',
            constraint=models.UniqueConstraint(fields=('item', 'enhancement', 'value', 'detail', 'display_text', 'tier'), name='unique_item_enhancement'),
        ),
    ]
