# Generated by Django 5.2.17 on 2026-08-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_enhancementrender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enhancementrender',
            name='detail',
            field=models.CharField(blank=True, help_text='Bonus types/qualifiers such as Insightful, Quality or Exceptional.', max_length=255),
        ),
        migrations.AddField(
            model_name='enhancementrender',
            name='value',
            field=models.CharField(blank=True, help_text='Magnitude for the search filter, e.g. +26% or +2 or +4.', max_length=255),
        ),
    ]
