# Generated by Django 5.2.17 on 2026-08-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_enhancementrender_detail_enhancementrender_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemenhancement',
            name='magnitude',
            field=models.FloatField(blank=True, help_text='Numeric magnitude parsed from the value for minimum-at-least searches, e.g. 22 from +22%; null when the value is not numeric.', null=True),
        ),
    ]
