# Generated by Django 5.2.17 on 2026-08-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_itemenhancement_magnitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='enhancementrender',
            name='raw_html',
            field=models.TextField(blank=True, default='', help_text='The exact output the wiki produced for this template call. Kept so parsing fixes can be re-applied locally with --reparse instead of asking the wiki again.'),
        ),
    ]
