# Generated by Django 5.2.17 on 2026-08-15 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_enhancementrender_raw_html'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnhancementRender',
        ),
    ]
