# Generated by Django 5.2.17 on 2026-08-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_enhancement_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enhancement',
            name='display_name',
            field=models.CharField(blank=True, help_text='Editable override shown to users everywhere the enhancement appears (dropdowns, item pages). Leave blank to use the wiki name. Never changes the name field above.', max_length=255),
        ),
        migrations.AlterField(
            model_name='enhancement',
            name='name',
            field=models.CharField(help_text='Canonical name from the wiki. Immutable after import; never edit this field.', max_length=255, unique=True),
        ),
    ]
