# Generated by Django 5.2.17 on 2026-08-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_enhancementvariant'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enhancement',
            constraint=models.UniqueConstraint(condition=models.Q(('display_name', ''), _negated=True), fields=('display_name',), name='unique_enhancement_display_name'),
        ),
    ]
