# Generated by Django 5.2.17 on 2026-08-15 19:09

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_enhancement_unique_enhancement_display_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enhancement',
            name='unique_enhancement_display_name',
        ),
        migrations.AddConstraint(
            model_name='enhancement',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Coalesce(django.db.models.functions.comparison.NullIf('display_name', models.Value('')), 'name'), name='unique_enhancement_effective_label'),
        ),
    ]
