# Generated by Django 5.2.17 on 2026-08-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_enhancement_unique_enhancement_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateTimeField(blank=True, help_text='Date the imported data reflects (snapshot capture date), not the date it was imported.', null=True)),
                ('loaded_at', models.DateTimeField(auto_now=True, help_text='When the database was last brought current.')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this row was last written by the importer.'),
        ),
        migrations.AddField(
            model_name='item',
            name='wiki_revision_timestamp',
            field=models.DateTimeField(blank=True, help_text='Wiki timestamp of the imported revision. Shows how fresh the content is versus the wiki; populated on new imports, null for rows imported before this field existed.', null=True),
        ),
    ]
