# Generated by Django 5.2.17 on 2026-08-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_syncstate_item_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='enchantment_tree',
            field=models.JSONField(blank=True, help_text="The parsed Enchantments cell tree (nested tiers, tooltips, alternatives) captured from the item's rendered wiki page. Used for display; null when the item predates the tree capture.", null=True),
        ),
        migrations.AddField(
            model_name='itemenhancement',
            name='possible',
            field=models.BooleanField(default=False, help_text="True when this is one of several mutually-exclusive options the item can have (e.g. 'A Mysterious Effect - can be any one of these 4 sets'), not a guaranteed effect."),
        ),
    ]
