# Generated by Django 5.2.17 on 2026-08-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_fix_rule_handler_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='armor_type',
            field=models.CharField(blank=True, help_text="Raw 'Armor Type' infobox value (e.g. 'Breastplate / Scalemail', 'Docent'); item_type holds the derived 'Armor: <Class>'.", max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='feat_requirement',
            field=models.CharField(blank=True, help_text="Raw 'Feat Requirement' infobox row used to classify armor (e.g. 'Light Armor Proficiency').", max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, help_text="Material shown in the infobox (e.g. 'Mithral'), tooltip description stripped.", max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='proficiency_class',
            field=models.CharField(blank=True, help_text="Weapon proficiency requirement row (e.g. 'Exotic Weapon Proficiency') or a shield's 'Proficiency' row.", max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='weapon_class',
            field=models.CharField(blank=True, help_text="Weapon proficiency class from 'Weapon Type: Bastard Sword / Slashing weapons', e.g. 'Slashing weapons'.", max_length=255),
        ),
    ]
