# Generated by Django 5.2.17 on 2026-08-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_item_armor_type_item_feat_requirement_item_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.CharField(blank=True, help_text='Searchable category derived at load: Armor, Clothing, Cosmetic, Jewelry, Quiver, Shield, Weapon. Blank for items whose infobox has no categorizable type row (e.g. eternal wands).', max_length=255),
        ),
    ]
