# Generated by Django 5.2.17 on 2026-08-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_item_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slot',
            field=models.CharField(blank=True, help_text="Equipment slot per the wiki's Equipment_slot page (e.g. 'Armor', 'Main Hand', 'Back', 'Finger'), derived from the category/type at load.", max_length=255),
        ),
    ]
