# Generated by Django 5.2.17 on 2026-08-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_item_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fetched_at',
            field=models.DateTimeField(blank=True, help_text="When we pulled this page from the wiki (the item file's fetched_at), i.e. when the imported data was captured. Paired with wiki_revision_timestamp so stale data can be traced to 'we never pulled it' vs 'the wiki changed after we pulled'.", null=True),
        ),
    ]
