# Generated by Django 5.2.17 on 2026-08-17 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_item_fetched_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnchantmentRule',
        ),
    ]
