# Generated by Django 5.2.17 on 2026-08-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_remove_enchantment_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemenchantment',
            name='raw_template',
        ),
    ]
