# Generated by Django 5.2.17 on 2026-08-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_remove_raw_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_category',
        ),
        migrations.AddField(
            model_name='item',
            name='item_class',
            field=models.CharField(blank=True, help_text='Template class from the wiki infobox: Armor, Clothing, Cosmetic, Jewelry, Quiver, Shield, Weapon. Blank for items whose infobox has no categorizable type row (e.g. eternal wands).', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='item_template',
            field=models.CharField(blank=True, help_text="Wikitext template name parsed at load (e.g. 'Named item').", max_length=255),
        ),
    ]
